#!/usr/bin/env python3
"""Compile the TypeScript sources and write the offline service worker.

Usage:  python3 build.py
Needs:  the TypeScript compiler (`npm install -g typescript`, or `npx tsc`).
Output: everything in app/ is the finished site; upload that folder to any static host.
"""
import hashlib, json, pathlib, subprocess, sys

root = pathlib.Path(__file__).parent
app = root / 'app'

tsc = ['tsc', '-p', str(root)]
try:
    subprocess.run(tsc, check=True)
except FileNotFoundError:
    subprocess.run(['npx', '--yes', '-p', 'typescript', 'tsc', '-p', str(root)], check=True)

files = sorted(
    p.relative_to(app).as_posix() for p in app.rglob('*')
    if p.is_file() and p.name != 'sw.js' and not p.name.startswith('.')
)
digest = hashlib.sha256()
for f in files:
    digest.update(f.encode()); digest.update((app / f).read_bytes())
version = digest.hexdigest()[:10]

sw = f"""// Generated by build.py. Caches the app so it opens and works with no connection.
const VERSION = '{version}';
const APP_CACHE = 'pff-coach-' + VERSION;
const FONT_CACHE = 'pff-coach-fonts';
const FILES = {json.dumps(['./'] + files)};

self.addEventListener('install', (e) => {{
  e.waitUntil(caches.open(APP_CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
}});

self.addEventListener('activate', (e) => {{
  e.waitUntil(caches.keys().then((keys) => Promise.all(
    keys.filter((k) => k.startsWith('pff-coach-') && k !== APP_CACHE && k !== FONT_CACHE).map((k) => caches.delete(k))
  )).then(() => self.clients.claim()));
}});

self.addEventListener('fetch', (e) => {{
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET') return;
  if (url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com') {{
    e.respondWith(caches.open(FONT_CACHE).then(async (c) => {{
      const hit = await c.match(e.request);
      const net = fetch(e.request).then((r) => {{ if (r.ok || r.type === 'opaque') c.put(e.request, r.clone()); return r; }}).catch(() => hit);
      return hit || net;
    }}));
    return;
  }}
  if (url.origin !== location.origin) return;
  e.respondWith(caches.match(e.request, {{ ignoreSearch: true }}).then((hit) => hit || fetch(e.request).catch(() => caches.match('./index.html'))));
}});
"""
(app / 'sw.js').write_text(sw)
print(f'Built {len(files)} files, cache version {version}')
